config/routes.rb
Gaia::Application.routes.draw do

  root :to => "home#index"
  resources :parameters do
    collection do
      get 'search'
    end
  end
    
end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  
  def self.search(page_number, page_size, filter = SearchFilter.new)
    
    if filter.empty?
      paginate(:page => page_number, :per_page => page_size)
    else
      query, params = filter.build_query
      where(query, *params).paginate(:page => page_number, :per_page => page_size)
    end  
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :layout => 'home'
  end
end

app/controllers/parameters_controller.rb
require 'pdf_generator'

class ParametersController < ApplicationController
  
  helper_method :get_page_size, :get_page_sizing_path
  
  def index
    @parameters = Parameter.search params[:page], get_page_size 

    respond_to do |format|
      format.html { render :index }
      format.xml { render :xml => @parameters }
      format.pdf { render :text => PdfGenerator.new.create_pdf(@parameters) }
    end
  end
  
  def search
    unless request.query_string.empty?
      @parameters = Parameter.search params[:page], get_page_size, SearchFilter.initialize_from(params)

      respond_to do |format|
        format.html { render :index }
        format.xml { render :xml => @parameters }
        format.pdf { render :text => PdfGenerator.new.create_pdf(@parameters) }
      end
    end
  end
  
  private
  
  def get_page_size
    params[:page_size] ||= 20
  end
  
  def get_page_sizing_path
    url_for(:only_path => false) + "?" + 
      request.query_string.gsub(/\&*page_size=[\d]*/, "").gsub(/\&*page=[\d]*/, "")
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parameter_helper.rb
module ParameterHelper
  class SearchFilter
    @@criteria_field_map = {
      "unit" => "unit", 
      "source" => "source", 
      "description" => "description"
    }

    def self.initialize_from params
      valid_criteria = params.select do |k,v|
        @@criteria_field_map.has_key?k and !v.nil? and !v.empty?
      end
      sc = new
      sc.instance_variable_set(:@criteria, Hash[valid_criteria.map {|k,v| [@@criteria_field_map[k], v]}])
      return sc
    end

    def empty?
      @criteria.nil? or @criteria.empty?
    end

    def build_query
      where_condition = @criteria.keys.first + @criteria.keys.drop(1).inject(" LIKE ?") {|q, p| q + " AND #{p} LIKE ?"}
      return where_condition, @criteria.values.map{|v| "%#{v}%"}
    end

  end
end

app/helpers/search_filter.rb
class SearchFilter
  @@criteria_field_map = {
    "unit" => "unit", 
    "source" => "source", 
    "description" => "description"
  }
  
  def self.initialize_from params
    valid_criteria = params.select do |k,v|
      @@criteria_field_map.has_key?k and !v.nil? and !v.empty?
    end
    sc = new
    sc.instance_variable_set(:@criteria, Hash[valid_criteria.map {|k,v| [@@criteria_field_map[k], v]}])
    return sc
  end
  
  def empty?
    @criteria.nil? or @criteria.empty?
  end
  
  def build_query
    where_condition = @criteria.keys.first + @criteria.keys.drop(1).inject(" LIKE ?") {|q, p| q + " AND #{p} LIKE ?"}
    return where_condition, @criteria.values.map{|v| "%#{v}%"}
  end
  
end

app/views/home/index.html.haml
.centered
		%h3 Welcome to the GAIA parameter database web application

		%h5 Please use the menu links to search or browse the database

app/views/layouts/_header.html.haml
.topbar
	%ul
		%li
			= image_tag('icrar_logo_black_small.jpg')
		%li
			%a{:href=>"#{root_path}"} GAIA PDB
		%li 
			%a{:href=>"#{search_parameters_path}"} Search
		%li 
			%a{:href=>"#{parameters_path}"} Browse

		#flash.span5
			- flash.each do |key, msg|
				%p{:class => "#{key} flash"}
				= msg
			.clear

%div.top-space

app/views/layouts/application.html.haml
%html
  %head
    %title= content_for?(:title) ? "GAIA Parameter Database - #{yield :title}" : "GAIA Parameter Database"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
  %body
    #header-container
      = render :partial => "layouts/header"
    
    #body-container
      = yield

app/views/layouts/home.html.haml
%html
  %head
    %title= content_for?(:title) ? "GAIA Parameter Database - #{yield :title}" : "GAIA Parameter Database"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
  %body
    #header-container
      = render :partial => "layouts/header"
    
    #body-container.home-body
      = yield

app/views/parameters/index.html.haml
.digg_pagination
	.page_info 
		= page_entries_info @parameters
	= will_paginate @parameters, :container => true
	%label Page size:
	%select{ :id => "page_size", :onchange => "window.location.href = '#{get_page_sizing_path}&page_size=' + $(this).val();" }
		= options_for_select ["10", "20", "50", "100"], get_page_size
	.export
		= link_to "Export as XML", params.merge(:format => :xml), :id => "export_xml"
		= link_to "Export as PDF", params.merge(:format => :pdf), :id => "export_pdf"
#search_results
	%table.zebra-striped
		%thead
			%th Unit
			%th Source
			%th Expression
			%th Description	
		%tbody
			- @parameters.each do |p|
				%tr.parameter
					%td
						= p.unit.empty? ? raw("&nbsp;") : p.unit
					%td
						= p.source.empty? ? raw("&nbsp;") : p.source
					%td
						= p.expression.empty? ? raw("&nbsp;") : p.expression
					%td
						= p.description

app/views/parameters/search.html.haml
%form#search
	%fieldset
		%legend Parameter search
		.clearfix
			%label{:for => 'unit'} Unit like
			.input
				%input{:name => 'unit', :type => 'text'}
		.clearfix
			%label{:for => 'source'} Source like
			.input
				%input{:name => 'source', :type => 'text'}
		.clearfix
			%label{:for => 'description'} Description like
			.input
				%input{:name => 'description', :type => 'text'}
	.actions
		%button.btn.primary{:type => 'submit'} Search

app/views/search/index.html.haml
.row
	.span16
		%form
			%fieldset
				%legend Parameter search
				.clearfix
					%label{:for => 'unit'} Unit like
					.input
						%input{:name => 'unit'}
				.clearfix
					%label{:for => 'source'} Source like
					.input
						%input{:name => 'source'}
				.clearfix
					%label{:for => 'description'} Description like
					.input
						%input{:name => 'description'}
			.actions
				%button.btn.primary{:type => 'submit'}Search